version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: fma
    restart: always
    environment:
      - POSTGRES_DB=fma_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5433:5432'
    volumes:
      - fma:/var/lib/postgresql/data
volumes:
  fma:
